### ISSUE TITLE
building form source stopped

### ISSUE THREAD

**Issue by berkalpb** [ProjectFTS/FTS_COIN#1]
I tried to build from source. It failed. This is the output during the make process. 

[make Result 2020-02-22.txt](https://github.com/ProjectFTS/FTS_COIN/files/4239493/make.Result.2020-02-22.txt)

**Comment by berkalpb** [comment]
Ive dropped a copy of the Build +parent folders here: 
https://drive.google.com/file/d/1dCKmOfM_SoTkqaT-p5rRERINEB9Am_Qg/view?usp=sharing

**Comment by berkalpb** [comment]
https://github.com/ProjectFTS/FTS_COIN/issues/2#issuecomment-592949412

**Comment by berkalpb** [comment]
looks like this worked. But I am being presumptuous here.

**Comment by berkalpb** [comment]
nope

**Comment by berkalpb** [comment]
> #2 (comment)

did not work

**Comment by berkalpb** [comment]
This is what happens
[MakeProcess2020-02-29.txt](https://github.com/ProjectFTS/FTS_COIN/files/4270475/MakeProcess2020-02-29.txt)

**Comment by berkalpb** [comment]
I think the problem is in the CMakeLists file somewhere around these lines:
https://github.com/ProjectFTS/FTS_COIN/blob/049d8a44b42d0869921a293cd3d81c70bff298b7/ftscoin-master/CMakeLists.txt#L193-L205

And this thread might have a solution for it. But I am not not a pro so :) ... . 
https://github.com/llvm-mirror/libcxx/commit/a0866c5fb5020d15c69deda94d32a7f982b88dc9

If I find the time this week I will try to make it work.  🤞

**Comment by ProjectFTS** [comment]
> I think the problem is in the CMakeLists file somewhere around these lines:
> https://github.com/ProjectFTS/FTS_COIN/blob/049d8a44b42d0869921a293cd3d81c70bff298b7/ftscoin-master/CMakeLists.txt#L193-L205
> 
> And this thread might have a solution for it. But I am not not a pro so :) ... .
> [llvm-mirror/libcxx@a0866c5](https://github.com/llvm-mirror/libcxx/commit/a0866c5fb5020d15c69deda94d32a7f982b88dc9)
> 
> If I find the time this week I will try to make it work.

Right on, well if you get it working let us know. Right now the issue seems to be isolated to your machine though, so i dont think the issue is in the code itself. As is we're having trouble replicating the issue though

**Comment by berkalpb** [comment]
Oh, I am just documenting my trials and errors trying to build it from source, here. 
Has anybody on a Mac OSX-Catalina tried to build it from source with more luck? 

At the moment I blame Catalina for the prebuilt version not working :D, also.

**Comment by wombatlabs** [comment]
I have built it on MacOS Catalina. Try building it and then when it errors out, open the code in a text editor and replace all instances of:
```
/usr/local/opt/llvm/lib/libc++fs.a
```

With this:
```
/usr/local/opt/llvm@8/lib/libc++fs.a
```

Then re-enter the build directory and run `make`.

**Comment by berkalpb** [comment]
That solved it. Thanks :)
