### ISSUE TITLE
Build variant not found

### ISSUE THREAD

**Issue by berkalpb** [ProjectFTS/FTS_COIN#2]
When running cmake, I get the error, that the build variant has not been found.

Check process' steps in attachment, if it might help. 
[Boost issue in process cmake protocoll 2020-02-22.txt](https://github.com/ProjectFTS/FTS_COIN/files/4239702/Boost.issue.in.process.cmake.protocoll.2020-02-22.txt)

**Comment by berkalpb** [comment]
Solved this. added `set(Boost_NO_BOOST_CMAKE ON)` to the CMakeList.

**Comment by ProjectFTS** [comment]
Nice so did you get it all working for yourself then? :)

**Comment by berkalpb** [comment]
unfotunately I am still struggeling with the `make` process. 

But I am trying annother approach. 

My terminal gave me this output. 

```
make[2]: *** No rule to make target `/usr/local/opt/llvm/lib/libc++fs.a', needed by `src/ftswallet'.  Stop.
make[1]: *** [src/CMakeFiles/zedwallet.dir/all] Error 2
make: *** [all] Error 2
```

so I changed the directory to look for - I guess 🙈- by doing as brew suggests: 
```
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
```
